# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='manage.proto',
    package='protobuf',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x0cmanage.proto\x12\x08protobuf\"M\n\x0cManageAction\x12(\n\x06modify\x18\x01 \x01(\x0b\x32\x16.protobuf.ModifyConfigH\x00\x12\n\n\x02Ty\x18\x02 \x01(\x05\x42\x07\n\x05value\"D\n\x0cModifyConfig\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\n\n\x02op\x18\x03 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x01(\tb\x06proto3'
)

_MANAGEACTION = _descriptor.Descriptor(
    name='ManageAction',
    full_name='protobuf.ManageAction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='modify', full_name='protobuf.ManageAction.modify', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='Ty', full_name='protobuf.ManageAction.Ty', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='value', full_name='protobuf.ManageAction.value',
            index=0, containing_type=None, fields=[]),
    ],
    serialized_start=26,
    serialized_end=103,
)

_MODIFYCONFIG = _descriptor.Descriptor(
    name='ModifyConfig',
    full_name='protobuf.ModifyConfig',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='protobuf.ModifyConfig.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='protobuf.ModifyConfig.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='op', full_name='protobuf.ModifyConfig.op', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='addr', full_name='protobuf.ModifyConfig.addr', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=105,
    serialized_end=173,
)

_MANAGEACTION.fields_by_name['modify'].message_type = _MODIFYCONFIG
_MANAGEACTION.oneofs_by_name['value'].fields.append(
    _MANAGEACTION.fields_by_name['modify'])
_MANAGEACTION.fields_by_name['modify'].containing_oneof = _MANAGEACTION.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['ManageAction'] = _MANAGEACTION
DESCRIPTOR.message_types_by_name['ModifyConfig'] = _MODIFYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ManageAction = _reflection.GeneratedProtocolMessageType('ManageAction', (_message.Message,), {
    'DESCRIPTOR': _MANAGEACTION,
    '__module__': 'manage_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.ManageAction)
})
_sym_db.RegisterMessage(ManageAction)

ModifyConfig = _reflection.GeneratedProtocolMessageType('ModifyConfig', (_message.Message,), {
    'DESCRIPTOR': _MODIFYCONFIG,
    '__module__': 'manage_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.ModifyConfig)
})
_sym_db.RegisterMessage(ModifyConfig)

# @@protoc_insertion_point(module_scope)
